name: 'static-website-action'
description: 'A Github action triggered by the static website push and combined with continuous actions.'
author: 'Eason Yang'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
